In [1]:
import keras

In [2]:
import torch

In [3]:
import numpy

In [5]:
numpy.sin(50)

-0.26237485370392877

In [6]:
import matplotlib

In [13]:
import numpy as np

In [8]:
n.round(15.6)

16.0

In [9]:
n = 15

In [10]:
n.round(18)

AttributeError: ignored

In [12]:
hussain.tan(20)

2.237160944224742

In [14]:
np = 18

In [15]:
import numpy as np
import pandas as pd


In [16]:
from numpy import *

In [17]:
sin(15)

0.6502878401571168

In [18]:
round(17.9)

18

In [19]:
from math import *
from numpy import *

In [20]:
import math as mt
import numpy as np

In [21]:
x = 15

In [22]:
x

15

In [23]:
y = 30


In [24]:
del x

In [25]:
x

NameError: ignored

In [ ]:
import numpy
import numpy as np
from numpy import *

In [1]:
from numpy import sin,cos

In [2]:
sin(15)

0.6502878401571168

In [3]:
tan(15)

NameError: ignored

In [4]:
import numpy as np
# random decimal number between 1 and 10
a = np.random.uniform(1,10)
a

5.161957274059248

In [5]:
# a 20 random decimal number between 1 and 10
b = np.random.uniform(1,10,20)
b

array([2.65708872, 3.07850809, 8.02748294, 6.43509832, 4.61172918,
       6.62786503, 8.05888969, 5.19121008, 5.65171934, 4.20028582,
       4.04220245, 3.73697017, 7.38007434, 2.29767921, 8.87775936,
       9.00713997, 3.36721379, 1.61890942, 3.52655006, 3.84014905])

In [6]:

# List of 3 of random numbers between 0 & 1
a = np.random.random(3)

a = np.random.rand(3)
a

array([0.90373817, 0.60390183, 0.19002543])

In [7]:

# matrix of 2X3 of random numbers between 0 & 1
a = np.random.random((2,3))

a = np.random.rand(5,3)
a


array([[0.89892354, 0.72520531, 0.13228276],
       [0.74865465, 0.69730619, 0.5879873 ],
       [0.66123278, 0.06082044, 0.32725714],
       [0.51850842, 0.41499726, 0.11195164],
       [0.12758826, 0.67909345, 0.50075421]])

In [19]:
AllList = []
for j in list([list(i) for i in a]) : 
  AllList.extend(j)
AllList = [i*1000 for i in AllList]
print(AllList)

[898.9235405185656, 725.20530806769, 132.28275882808916, 748.6546535243714, 697.3061908447643, 587.987301655245, 661.232778758662, 60.82044289584165, 327.25714073034726, 518.5084153703978, 414.99725854707725, 111.95163607666458, 127.58825544448283, 679.0934538261456, 500.7542128914094]


In [20]:
RoundList= [np.round(i) for i in AllList]
print(RoundList)

[899.0, 725.0, 132.0, 749.0, 697.0, 588.0, 661.0, 61.0, 327.0, 519.0, 415.0, 112.0, 128.0, 679.0, 501.0]


In [22]:
RoundList= [np.round(i,2) for i in AllList]
print(RoundList)

[898.92, 725.21, 132.28, 748.65, 697.31, 587.99, 661.23, 60.82, 327.26, 518.51, 415.0, 111.95, 127.59, 679.09, 500.75]


In [23]:
np.round(15.1)

15.0

In [24]:
np.round(15.9)

16.0

In [25]:
np.floor(15.1),np.floor(15.9)

(15.0, 15.0)

In [26]:
np.ceil(15.1),np.ceil(15.9)

(16.0, 16.0)

In [ ]:
from pandas import read_csv

In [27]:
import pandas as pd

In [33]:
data  = read_csv('/content/Airline_Delay_Cause.csv')

In [42]:
type(data)

pandas.core.frame.DataFrame

In [45]:
# del data

In [30]:
def CircleArea(r) :
  return 3.14*(r**2)

In [31]:
ThisArea = CircleArea(15)

In [32]:
ThisArea

706.5

In [46]:
data.head()

NameError: ignored

In [35]:
data.shape

(318017, 21)

In [36]:
data.describe()

year          month    arr_flights      arr_del15  \
count  318017.000000  318017.000000  317524.000000  317285.000000   
mean     2012.450957       6.497844     381.766670      72.905076   
std         5.678296       3.459423    1027.156722     198.936754   
min      2003.000000       1.000000       1.000000       0.000000   
25%      2007.000000       3.000000      59.000000       9.000000   
50%      2012.000000       6.000000     120.000000      23.000000   
75%      2018.000000      10.000000     273.000000      56.000000   
max      2022.000000      12.000000   21977.000000    6377.000000   

          carrier_ct     weather_ct         nas_ct    security_ct  \
count  317525.000000  317523.000000  317529.000000  317529.000000   
mean       21.073149       2.616407      24.005228       0.179037   
std        47.671580       9.968640      85.113757       0.844834   
min         0.000000       0.000000      -0.010000       0.000000   
25%         3.000000       0.000000       1.680000       0.000000   
50%         8.190000       0.580000       5.490000       0.000000   
75%        19.690000       2.000000      15.350000       0.000000   
max      1792.070000     717.940000    4091.270000      80.560000   

       late_aircraft_ct  arr_cancelled   arr_diverted      arr_delay  \
count     317529.000000  317529.000000  317527.000000  317523.000000   
mean          24.975734       7.207257       0.867674    4209.989113   
std           75.275223      37.216301       3.915772   12519.021012   
min            0.000000       0.000000       0.000000       0.000000   
25%            1.640000       0.000000       0.000000     436.000000   
50%            5.860000       1.000000       0.000000    1201.000000   
75%           17.040000       4.000000       1.000000    3080.000000   
max         1885.470000    4951.000000     256.000000  433687.000000   

       carrier_delay  weather_delay      nas_delay  security_delay  \
count  317525.000000  317529.000000  317529.000000   317527.000000   
mean     1286.577224     220.567542    1099.516422        7.214845   
std      3515.417309     861.521440    4636.475908       38.854685   
min         0.000000       0.000000     -19.000000        0.000000   
25%       148.000000       0.000000      56.000000        0.000000   
50%       437.000000      25.000000     203.000000        0.000000   
75%      1100.000000     159.000000     602.000000        0.000000   
max    196944.000000   57707.000000  238440.000000     3760.000000   

       late_aircraft_delay  
count        317529.000000  
mean           1596.062993  
std            4924.950687  
min               0.000000  
25%              79.000000  
50%             351.000000  
75%            1110.000000  
max          148181.000000

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 318017 entries, 0 to 318016
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   year                 318017 non-null  int64  
 1   month                318017 non-null  int64  
 2   carrier              318013 non-null  object 
 3   carrier_name         318013 non-null  object 
 4   airport              318014 non-null  object 
 5   airport_name         318017 non-null  object 
 6   arr_flights          317524 non-null  float64
 7   arr_del15            317285 non-null  float64
 8   carrier_ct           317525 non-null  float64
 9   weather_ct           317523 non-null  float64
 10  nas_ct               317529 non-null  float64
 11  security_ct          317529 non-null  float64
 12  late_aircraft_ct     317529 non-null  float64
 13  arr_cancelled        317529 non-null  float64
 14  arr_diverted         317527 non-null  float64
 15  arr_delay        

In [39]:
YearList = data['year'].tolist()
len(YearList)

318017

In [40]:
set(YearList)

{2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022}

In [41]:
data['year'].unique()

array([2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012,
       2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003])

In [ ]:
data.b

In [43]:
AllYears = data['year']
type(AllYears)

pandas.core.series.Series

In [44]:
AllYears.value_counts()

2019    20946
2021    19954
2007    19518
2008    18967
2020    18859
2006    18090
2009    17687
2010    17575
2018    17135
2005    17024
2004    16705
2013    16089
2011    15585
2012    14387
2014    13980
2015    13528
2017    12518
2016    12217
2003     8763
2022     8490
Name: year, dtype: int64